# 三轴加速度动作识别

In [2]:
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
df_data1 = pd.read_csv(r'UpStairsAccelerometer.csv')#数据使用“SensorRecord”采集android三轴加速度传感器信息
del df_data1['Milliseconds']
df_data1_5 = pd.read_csv(r'1.5LeftUpStairsAccelerometer.csv')
del df_data1_5['Milliseconds']
df_data2 = pd.read_csv(r'DownStairsAccelerometer.csv')
del df_data2['Milliseconds']
df_data3 = pd.read_csv(r'FlatWalkAccelerometer.csv')
del df_data3['Milliseconds']
df_data01 = pd.read_csv(r'StandAccelerometer.csv')
del df_data01['Milliseconds']
df_data02 = pd.read_csv(r'UpElevatorAccelerometer.csv')
del df_data02['Milliseconds']
df_data03 = pd.read_csv(r'DownElevatorAccelerometer.csv')
del df_data03['Milliseconds']
df_data=pd.concat([df_data1,df_data1_5,df_data2,df_data3,df_data01,df_data02,df_data03])

df_label1 = pd.read_csv(r'UpStairsAccelerometerLabel.csv')
df_label1_5 = pd.read_csv(r'1.5LeftUpStairsAccelerometerLabel.csv')
df_label2 = pd.read_csv(r'DownStairsAccelerometerLabel.csv')
df_label3 = pd.read_csv(r'FlatWalkAccelerometerLabel.csv')
df_label01 = pd.read_csv(r'StandAccelerometerLabel.csv')
df_label02 = pd.read_csv(r'UpElevatorAccelerometerLabel.csv')
df_label03 = pd.read_csv(r'DownElevatorAccelerometerLabel.csv')
df_label=pd.concat([df_label1,df_label1_5,df_label2,df_label3,df_label01,df_label02,df_label03])

In [3]:
df_label02.values.shape

(2224, 1)

In [4]:
x_train, x_test, y_train, y_test = train_test_split(df_data, df_label, test_size=0.1)

In [5]:
x_train.shape[0]

74877

In [6]:
x_test.shape[0]

8320

In [7]:
x_test.shape[0]/df_data.shape[0]

0.10000360589925117

In [8]:
outputpath='total.csv'#其中：index是否要索引，header是否要列名，True就是需要
df_data.to_csv(outputpath,sep=',',index=False,header=False)

outputpath='totalLabel.csv'
df_label.to_csv(outputpath,sep=',',index=False,header=False)


In [9]:
outputpath='x_train.csv'#其中：index是否要索引，header是否要列名，True就是需要
x_train.to_csv(outputpath,sep=',',index=False,header=False)

outputpath=' x_test.csv'
x_test.to_csv(outputpath,sep=',',index=False,header=False)

outputpath='y_train.csv'#其中：index是否要索引，header是否要列名，True就是需要
y_train.to_csv(outputpath,sep=',',index=False,header=False)

outputpath=' y_test.csv'
y_test.to_csv(outputpath,sep=',',index=False,header=False)

In [10]:
x_train=x_train.values
y_train=y_train.values
x_test=x_test.values
y_test=y_test.values

In [11]:
import time
time_start=time.time()
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, input_dim=3, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(4, activation='softmax')
])
#输入层3维样本X，Y，Z，神经元分别个不同的层，然后随机失活dropout=0.2,最后计算结果
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
#WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>
#pd.DataFrame2Numpy
#优化器使用Adam优化算法，交叉熵损失函数，学习率0.001，精度评价模型
model.fit(x_train, y_train, batch_size=4, epochs=9)
#训练
time_end=time.time()
print('time cost',time_end-time_start,'s')

Train on 74877 samples
Epoch 1/9
74877/74877 [==============================] - 289s 4ms/sample - loss: 0.8926 - accuracy: 0.6210 - l
Epoch 2/9
74877/74877 [==============================] - 251s 3ms/sample - loss: 0.8210 - accuracy: 0.6570
Epoch 3/9
74877/74877 [==============================] - 224s 3ms/sample - loss: 0.8007 - accuracy: 0.6665 - loss: 0.8006 - accuracy: 
Epoch 5/9
74877/74877 [==============================] - 211s 3ms/sample - loss: 0.7956 - accuracy: 0.6693
Epoch 6/9
74877/74877 [==============================] - 245s 3ms/sample - loss: 0.7897 - accuracy: 0.6710 - los - ETA
Epoch 7/9
74877/74877 [==============================] - 332s 4ms/sample - loss: 0.7889 - accuracy: 0.6742
Epoch 8/9
74877/74877 [==============================] - 324s 4ms/sample - loss: 0.7843 - accuracy: 0.6734
Epoch 9/9
74877/74877 [==============================] - 436s 6ms/sample - loss: 0.7867 - accuracy: 0.67311:00  - ETA: 54s - loss: 0.7867  - ETA: 52s - loss: 0.7863 - accuracy: - ETA: 

差强人意，但是科学就是需要深究琢磨，严谨认真，数据要有可重复性，要真实，结果不行呀，0.6674%准确率跟瞎蒙（1/4=0.25）还是挺有用的，但是还需要改进。一定有改进空间！或者模型使用不恰当，要改进！先进行模型的保存。

In [33]:
model.save('AcceleratometerSaveHDF5.h5')

In [34]:
x_test[0:3,:]

array([[13.218353  , -1.0570221 ,  1.8114014 ],
       [ 3.52742   , -2.1840515 ,  0.59106445],
       [-0.88734436,  5.7026978 ,  8.102127  ]])

In [35]:
y_test[0:3,:]#谁标签，理论上概率最大

array([[1],
       [3],
       [0]], dtype=int64)

In [36]:
model.predict(x_test[0:3,:])#结果是[0,1,2,3]分别对应的概率，四个数字中概率最大的分别对应是上面的y_test

array([[1.81643032e-02, 3.93628240e-01, 1.40620068e-01, 4.47587311e-01],
       [5.27030381e-04, 2.23062441e-01, 1.23243004e-01, 6.53167486e-01],
       [9.41703796e-01, 5.34949219e-03, 6.17601443e-03, 4.67707589e-02]],
      dtype=float32)

In [37]:
model.evaluate(x_test[0:2333,:], y_test[0:2333,:])

2333/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.7618245628837654, 0.6965281]

In [38]:
from tensorflow.keras.models import load_model
classifier = load_model('AcceleratometerSaveHDF5.h5') 

In [39]:
classifier.evaluate(x_test[0:666,:], y_test[0:666,:])

666/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.7252728291102, 0.7177177]

In [40]:
classifier.predict(x_test[0:3,:])#结果和前面一样

array([[1.81643032e-02, 3.93628240e-01, 1.40620068e-01, 4.47587311e-01],
       [5.27030381e-04, 2.23062441e-01, 1.23243004e-01, 6.53167486e-01],
       [9.41703796e-01, 5.34949219e-03, 6.17601443e-03, 4.67707589e-02]],
      dtype=float32)

In [41]:
df_data2=df_data2.values

In [45]:
classifier.predict(df_data2)[0:100,:]#理论上应该全是2即第三个概率最大

array([[0.23205309, 0.3025043 , 0.31694454, 0.14849806],
       [0.26999474, 0.2966064 , 0.2672821 , 0.16611679],
       [0.36004537, 0.26369563, 0.21334149, 0.16291746],
       [0.41926947, 0.24285541, 0.18701887, 0.15085627],
       [0.35223493, 0.25784862, 0.23016664, 0.15974984],
       [0.3052736 , 0.2744365 , 0.2582133 , 0.16207656],
       [0.27389857, 0.2828673 , 0.28428376, 0.1589503 ],
       [0.27333185, 0.2809744 , 0.28671327, 0.15898058],
       [0.26547742, 0.28401688, 0.29309148, 0.15741421],
       [0.25111577, 0.2862169 , 0.3036244 , 0.15904298],
       [0.22510254, 0.3019061 , 0.31830806, 0.15468329],
       [0.22103204, 0.30086675, 0.31917575, 0.15892555],
       [0.22478166, 0.29843   , 0.31847957, 0.15830867],
       [0.23228915, 0.292251  , 0.31656614, 0.1588937 ],
       [0.23364858, 0.29425108, 0.3161498 , 0.15595055],
       [0.22877796, 0.30256444, 0.3173927 , 0.15126485],
       [0.23123395, 0.30436048, 0.31641373, 0.14799187],
       [0.23781505, 0.30370536,

有错很正常，前面正确率是67.25%，但是比瞎蒙1/4=25%好很多了，但是还不够好。